DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS contact;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	password TEXT NOT NULL
);

CREATE TABLE contact (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	user_id INTEGER NOT NULL,
	name TEXT NOT NULL,
	surname TEXT,
	email TEXT,
	num TEXT NOT NULL,
	FOREIGN KEY (user_id) REFERENCES user (id)
);